

public class Const {


    public static int REQUEST_AUTHORIZATION = 100,REQUEST_REGISTRATION = 101,REQUEST_ADD_FRIEND = 102;

    public static int ERROR_ACCOUNT_NOT_EXIST = 300,ERROR_LOGIN_ALREADY_TAKEN = 301,INVALID_USERNAME_OR_PASSWORD=302;

    public static int SUCCESS_OPERATION = 200;





}
